
import mongoose from "mongoose";

/*
============================================================
JOB ORDER MODEL
============================================================

Relationship:

Customer
   ↓
Customer Item
   ↓
Job Order

A Job Order stores:

1. Reference to the original Customer
2. Reference to the original Customer Item
3. Customer snapshot
4. Customer Item snapshot

Snapshots preserve historical information even if the
Customer or Customer Item is changed later.
============================================================
*/


// ============================================================
// CUSTOMER SNAPSHOT
// ============================================================

const customerSnapshotSchema = new mongoose.Schema(
  {
    code: {
      type: String,
      default: "",
      trim: true,
      uppercase: true,
    },

    name: {
      type: String,
      default: "",
      trim: true,
      uppercase: true,
    },

    address: {
      type: String,
      default: "",
      trim: true,
    },

    contactPerson: {
      type: String,
      default: "",
      trim: true,
    },

    orderTypes: {
      type: String,
      default: "",
      trim: true,
    },

    limits: {
      type: String,
      default: "",
      trim: true,
    },

    receipts: {
      type: String,
      default: "",
      trim: true,
    },

    vatType: {
      type: String,
      default: "",
      trim: true,
    },

    paymentTerms: {
      type: String,
      default: "",
      trim: true,
    },

    paymentMethod: {
      type: String,
      default: "",
      trim: true,
    },
  },
  {
    _id: false,
  }
);


// ============================================================
// OPERATION SNAPSHOT
// ============================================================

const operationSnapshotSchema = new mongoose.Schema(
  {
    step: {
      type: Number,
      required: true,
      min: 1,
    },

    processFlow: {
      type: String,
      default: "",
      trim: true,
    },

    remarks: {
      type: String,
      default: "",
      trim: true,
    },
  },
  {
    _id: false,
  }
);


// ============================================================
// CUSTOMER ITEM SNAPSHOT
// ============================================================

const customerItemSnapshotSchema = new mongoose.Schema(
  {
    code: {
      type: String,
      default: "",
      trim: true,
      uppercase: true,
    },

    productType: {
      type: String,
      default: "",
      trim: true,
    },

    name: {
      type: String,
      default: "",
      trim: true,
    },

    description: {
      type: String,
      default: "",
      trim: true,
    },

    uom: {
      type: String,
      default: "PC",
      trim: true,
      uppercase: true,
    },

    widthMM: {
      type: Number,
      default: 0,
      min: 0,
    },

    lengthMM: {
      type: Number,
      default: 0,
      min: 0,
    },

    heightMM: {
      type: Number,
      default: 0,
      min: 0,
    },

    printingType: {
      type: String,
      default: "",
      trim: true,
    },

    jointType: {
      type: String,
      default: "",
      trim: true,
    },

    materialSpecification: {
      type: {
        type: String,
        default: "",
        trim: true,
      },

      paperCombination: {
        type: String,
        default: "",
        trim: true,
      },

      fluteTest: {
        type: String,
        default: "",
        trim: true,
      },

      boardSize: {
        type: String,
        default: "",
        trim: true,
      },
    },

    productionTools: {
      printingPlate: {
        type: String,
        default: "",
        trim: true,
      },

      inksColor: {
        type: String,
        default: "",
        trim: true,
      },

      dcBlade: {
        type: String,
        default: "",
        trim: true,
      },
    },

    operations: {
      type: [operationSnapshotSchema],
      default: [],
    },
  },
  {
    _id: false,
  }
);


// ============================================================
// MAIN JOB ORDER SCHEMA
// ============================================================

const jobOrderSchema = new mongoose.Schema(
  {
    // ========================================================
    // JOB ORDER NUMBER
    // ========================================================
    // Automatically generated by the Job Order controller.
    // Example: JO-2026-00001

    jobOrderNumber: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      uppercase: true,
    },


    // ========================================================
    // PO NUMBER
    // ========================================================

    poNumber: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
    },


    // ========================================================
    // MASTER DATA REFERENCES
    // ========================================================

    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
      index: true,
    },

    customerItem: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "CustomerItem",
      required: true,
      index: true,
    },


    // ========================================================
    // ORDER INFORMATION
    // ========================================================

    quantity: {
      type: Number,
      required: true,
      min: 0.01,
    },

    // Automatically copied from Customer Item.
    uom: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
    },

    orderDate: {
      type: Date,
      required: true,
      default: Date.now,
    },

    dueDate: {
      type: Date,
      default: null,
    },

    priority: {
      type: String,
      enum: [
        "Low",
        "Medium",
        "High",
        "Urgent",
      ],
      default: "Medium",
    },

    status: {
      type: String,
      enum: [
        "Pending",
        "Confirmed",
        "In Production",
        "Completed",
        "Cancelled",
      ],
      default: "Pending",
      index: true,
    },

    remarks: {
      type: String,
      default: "",
      trim: true,
    },


    // ========================================================
    // CUSTOMER SNAPSHOT
    // ========================================================

    customerSnapshot: {
      type: customerSnapshotSchema,
      required: true,
    },


    // ========================================================
    // CUSTOMER ITEM SNAPSHOT
    // ========================================================

    customerItemSnapshot: {
      type: customerItemSnapshotSchema,
      required: true,
    },


    // ========================================================
    // USER TRACKING
    // ========================================================

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true,
  }
);


// ============================================================
// INDEXES
// ============================================================

// Customer Job Orders
jobOrderSchema.index({
  customer: 1,
  createdAt: -1,
});

// Customer Item Job Orders
jobOrderSchema.index({
  customerItem: 1,
  createdAt: -1,
});

// Job Order Status
jobOrderSchema.index({
  status: 1,
  createdAt: -1,
});

// PO Number search
jobOrderSchema.index({
  poNumber: 1,
});


// ============================================================
// MODEL
// ============================================================

const JobOrder = mongoose.model(
  "JobOrder",
  jobOrderSchema
);

export default JobOrder;

